/* Repeat */
export const START_GETTING_REPEAT_DETAILS = 'START_GETTING_REPEAT_DETAILS'
export const GET_REPEAT_DETAILS_SUCCESS = 'GET_REPEAT_DETAILS_SUCCESS'
export const GET_REPEAT_DETAILS_ERROR = 'GET_REPEAT_DETAILS_ERROR'
export const START_CLEANING_REPEAT_DETAILS = 'START_CLEANING_REPEAT_DETAILS'
export const CLEAN_REPEAT_DETAILS_SUCCESS = 'CLEAN_REPEAT_DETAILS_SUCCESS'
export const CLEAN_REPEAT_DETAILS_ERROR = 'CLEAN_REPEAT_DETAILS_ERROR'
