/* Repeat */
export const START_GETTING_REPEAT_DETAILS = 'START_GETTING_REPEAT_DETAILS'
export const GET_REPEAT_DETAILS_SUCCESS = 'GET_REPEAT_DETAILS_SUCCESS'
export const GET_REPEAT_DETAILS_ERROR = 'GET_REPEAT_DETAILS_ERROR'
export const START_CLEANING_REPEAT_DETAILS = 'START_CLEANING_REPEAT_DETAILS'
export const CLEAN_REPEAT_DETAILS_SUCCESS = 'CLEAN_REPEAT_DETAILS_SUCCESS'
export const CLEAN_REPEAT_DETAILS_ERROR = 'CLEAN_REPEAT_DETAILS_ERROR'
/* Estimate */
export const START_GETTING_ESTIMATE_DETAILS = 'START_GETTING_ESTIMATE_DETAILS'
export const GET_ESTIMATE_DETAILS_SUCCESS = 'GET_ESTIMATE_DETAILS_SUCCESS'
export const GET_ESTIMATE_DETAILS_ERROR = 'GET_ESTIMATE_DETAILS_ERROR'
export const START_CLEANING_ESTIMATE_DETAILS = 'START_CLEANING_ESTIMATE_DETAILS'
export const CLEAN_ESTIMATE_DETAILS_SUCCESS = 'CLEAN_ESTIMATE_DETAILS_SUCCESS'
export const CLEAN_ESTIMATE_DETAILS_ERROR = 'CLEAN_ESTIMATE_DETAILS_ERROR'
