services:
  api:
    image: codnas-repeats:api-1.0.0
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: codnas-repeats
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "true"
      MAIL_USERNAME:
      MAIL_PASSWORD:
      REDIS_URL: redis://redis:6379/0
    depends_on:
     - redis
    command: gunicorn -b :5000 service:app
  web:
    image: codnas-repeats:web-1.0.0
    ports:
      - "80:80"
  db:
    image: codnas-repeats:db-1.0.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: codnas-repeats
  redis:
    image: "redis:alpine"
    ports:
      - "6739:6739"
  worker:
    image: codnas-repeats:api-1.0.0
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: codnas-repeats
      MAIL_SERVER: smtp.googlemail.com
      MAIL_PORT: 587
      MAIL_USE_TLS: "true"
      MAIL_USERNAME: 
      MAIL_PASSWORD:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    command: rq worker codnas-repeats-tasks --url redis://redis:6379/0
